# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G

# Fabric Properties
	# check these on https://fabricmc.net/versions.html
	minecraft_version=26.1-snapshot-3
	yarn_mappings=1.21.6+build.1
	loader_version=0.18.4

# Fabric API
  	java_version=21

# Mod Properties
	mod_version = 0.17.0
	maven_group = org.ladysnake
	archives_base_name = elmendorf

# Metadata
	mod_name = Elmendorf
	owners = Ladysnake

# Dependencies
	fabric_version=0.141.3+26.1
	cca_version=8.0.0-SNAPSHOT
